### ISSUE TITLE
After specifying folder - FileNotFoundError

### ISSUE THREAD

**Issue by victoria-sommer** [milxss/universal_log_parser#3]
➜  universal_stealer_log_parser git:(main) ✗ python3 main.py
Specify the main folder: ~/5
The main folder is: ~/5
Traceback (most recent call last):
  File "/Users/dkvicsom/universal_stealer_log_parser/main.py", line 18, in <module>
    main()
  File "/Users/dkvicsom/universal_stealer_log_parser/main.py", line 11, in main
    process_cc(main_folder)
  File "/Users/dkvicsom/universal_stealer_log_parser/cc_parser.py", line 94, in process_cc
    with open(output_file_path, 'w') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '~/5/merged_cc_info_racoon.txt'

Anyone know what is going on wrong here? Am I specifying the log folder incorrectly? Thank you

**Comment by cubetech126** [comment]
how am i supposed to read anything if you striked through all of the text
